language: node_js
cache:
  directories:
  - "$HOME/code/.npm"
  - "$HOME/code/.yarn-cache"
  - node_modules
notifications:
  webhooks:
    urls:
    - https://api.ghostinspector.com/v1/suites/5693b09b0077af792c1a6ad5/execute/?apiKey=fa38baa2759df4b34f5330b34331d4c5a87b6d57
    on_success: always
    on_failure: never
branches:
  only:
  - master
node_js:
- '6'
before_install:
- openssl aes-256-cbc -K $encrypted_97b3e9460dc1_key -iv $encrypted_97b3e9460dc1_iv
  -in deploy-key.enc -out deploy-key -d
- time npm i -g yarn --cache-min 999999999
install:
- bash travis_scripts/install.sh
script:
- time cd code && yarn test
before_deploy:
  - rm -rf .git && rm -rf .gitignore
deploy:
  provider: script
  script: sh ./travis_scripts/deploy.sh
  skip_cleanup: true
  on:
      branch: master
notifications:
  webhooks: http://ludobermejo.es:9100
  on_success: always
  on_failure: always
  on_start: always
