language: node_js
cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.yarn-cache"
  - node_modules
notifications:
  webhooks:
    urls:
    - https://api.ghostinspector.com/v1/suites/5693b09b0077af792c1a6ad5/execute/?apiKey=fa38baa2759df4b34f5330b34331d4c5a87b6d57
    on_success: always
    on_failure: never
branches:
  only:
  - master
node_js:
- '6'
before_install:
- openssl aes-256-cbc -K $encrypted_97b3e9460dc1_key -iv $encrypted_97b3e9460dc1_iv
  -in deploy-key.enc -out deploy-key -d
- time npm i -g yarn --cache-min 999999999
install:
- time yarn
- set -x # Show the output of the following commands (useful for debugging)
  # Import the SSH deployment key
- openssl aes-256-cbc -K $encrypted_97b3e9460dc1_key -iv $encrypted_97b3e9460dc1_iv -in deploy-key.enc -out deploy-key -d
-  rm deploy-key.enc # Don't need it anymore
-  chmod 600 deploy-key
-  mv deploy-key ~/.ssh/id_rsa

script:
- time yarn test
